language: php

before_script: 
    - chmod +x phpUtils/phpunit
    - export PATH=$PATH:phpUtils/

script:
    - phpunit test/CalculatorTest.php
    - phpunit --coverage-html . test/CalculatorTest.php
